### ISSUE TITLE
Error when downloading NCBITaxon

### ISSUE THREAD

**Issue by anitacaron** [OBOFoundry/OBO-Dashboard#130]
```bash
ERROR:root:Failed to download ncbitaxon from http://purl.obolibrary.org/obo/ncbitaxon.owl
Traceback (most recent call last):
  File "/Users/anitac/Documents/GitHub/OBO-Dashboard/./util/dashboard_config.py", line 195, in prepare_ontologies
    urllib.request.urlretrieve(ourl, ont_path)
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 278, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 702545920 out of 1579227873 bytes>
```

**Comment by matentzn** [comment]
I had someone report this error on slack a few days back, but it did work for me.. maybe a temporary thing?

**Comment by anitacaron** [comment]
I just tried to run the dashboard locally before opening this issue. And I also tried many times on the server. I'll check it later.

**Comment by matentzn** [comment]
I tried it again a 3 times.. It worked in all cases..


```
 wget http://purl.obolibrary.org/obo/ncbitaxon.owl
--2024-08-16 11:41:49--  http://purl.obolibrary.org/obo/ncbitaxon.owl
Resolving purl.obolibrary.org (purl.obolibrary.org)... 2606:4700::6812:df, 2606:4700::6812:1df, 104.18.0.223, ...
Connecting to purl.obolibrary.org (purl.obolibrary.org)|2606:4700::6812:df|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.owl [following]
--2024-08-16 11:41:50--  https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.owl
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/obophenotype/ncbitaxon/releases/download/v2024-07-03/ncbitaxon.owl [following]
--2024-08-16 11:41:51--  https://github.com/obophenotype/ncbitaxon/releases/download/v2024-07-03/ncbitaxon.owl
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/43841146/81e23de6-3df8-4b19-97b7-51a0a8c85bee?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240816%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240816T084151Z&X-Amz-Expires=300&X-Amz-Signature=e06d5a060d421d29420dab9a95f62faa551749747cd61a30e0276a31b258fe47&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=43841146&response-content-disposition=attachment%3B%20filename%3Dncbitaxon.owl&response-content-type=application%2Foctet-stream [following]
--2024-08-16 11:41:51--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/43841146/81e23de6-3df8-4b19-97b7-51a0a8c85bee?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240816%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240816T084151Z&X-Amz-Expires=300&X-Amz-Signature=e06d5a060d421d29420dab9a95f62faa551749747cd61a30e0276a31b258fe47&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=43841146&response-content-disposition=attachment%3B%20filename%3Dncbitaxon.owl&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1579227873 (1.5G) [application/octet-stream]
Saving to: ‘ncbitaxon.owl’

ncbitaxon.owl     100%[==========>]   1.47G  48.7MB/s    in 31s     

2024-08-16 11:42:22 (49.3 MB/s) - ‘ncbitaxon.owl’ saved [1579227873/1579227873]
```

Maybe this is hitting some limit of GitHub somehow.. :/

**Comment by anitacaron** [comment]
Oh yeah, wget might work, but the Python code is blocking somehow.

**Comment by matentzn** [comment]
Default timeout settings?
