### ISSUE TITLE
ERROR: unable to run check 7 for ONT

### ISSUE THREAD

**Issue by anitacaron** [OBOFoundry/OBO-Dashboard#137]
When I develop, locally, new features, I came across with this error when running the Relationship report. I'm using ROBOT 1.9.6, but also tried 1.9.5. I'm not using ODK. I'm running the dashboard on the server to check if the issue persists. The last dashboard version on 2024-10-01, which uses ODK, didn't have this issue.

```bash
CAUSE:
An error occurred while calling o22.iterator. Trace:
java.lang.reflect.InaccessibleObjectException: Unable to make public java.util.Iterator java.util.Collections$EmptySet.iterator() accessible: module java.base does not "opens java.util" to unnamed module @43dbe4cf
    at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
            at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
                at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:203)
                    at java.base/java.lang.reflect.Method.setAccessible(Method.java:197)
                        at py4j.reflection.MethodInvoker$1.run(MethodInvoker.java:240)
                            at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
                                at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:238)
                                    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
                                        at py4j.Gateway.invoke(Gateway.java:282)
                                            at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
                                                at py4j.commands.CallCommand.execute(CallCommand.java:79)
                                                    at py4j.GatewayConnection.run(GatewayConnection.java:238)
                                                        at java.base/java.lang.Thread.run(Thread.java:1583)
```

The error is raised on the line [fp_007.py#L103](https://github.com/OBOFoundry/OBO-Dashboard/blob/32c9dbb2be693b38b551680504f145e1104ae655/util/dashboard/fp_007.py#L103) because the method `ontology.getObjectPropertiesInSignature()` returns empty. I've tested for many large ontologies, for ex. CL, UBERON, and all with the same issue.

**Comment by matentzn** [comment]
I would check that the java and py4j versions used on the server are the same as in ODK
