### ISSUE TITLE
Error in loop when try to download ontology not found

### ISSUE THREAD

**Issue by anitacaron** [OBOFoundry/OBO-Dashboard#149]
Message error

```
Traceback (most recent call last):
  File "/Users/anitacaron/Documents/GitHub/OBO-Dashboard/util/lib.py", line 589, in download_file
    response.raise_for_status()
  File "/Users/anitacaron/Documents/GitHub/OBO-Dashboard/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/PlantPhenoOntology/ppo/master/releases/2018-10-26/ppo.owl
ERROR:root:Failed to download http://purl.obolibrary.org/obo/ppo.owl: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/PlantPhenoOntology/ppo/master/releases/2018-10-26/ppo.owl
Traceback (most recent call last):
  File "/Users/anitacaron/Documents/GitHub/OBO-Dashboard/util/lib.py", line 589, in download_file
    response.raise_for_status()
  File "/Users/anitacaron/Documents/GitHub/OBO-Dashboard/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/PlantPhenoOntology/ppo/master/releases/2018-10-26/ppo.owl
ERROR:root:Failed to download http://purl.obolibrary.org/obo/ppo.owl: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/PlantPhenoOntology/ppo/master/releases/2018-10-26/ppo.owl
```

**Comment by anitacaron** [comment]
There's already an [issue in the ontology](https://github.com/PlantPhenoOntology/ppo/issues/103) asking to update the purl config.
